config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "front/pages#welcome"

  namespace :workroom, path: "workroom" do
    root to: 'lists#new'
    get "sign_in" => "sessions#new"

    resources :lists do
      member do
        get :download
      end
      collection do
        get :state
        get :check_company_count
      end
    end

    resources :industries, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :naics, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :sics, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :rankings, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :sessions, only: [:create] do
      collection do
        delete :destroy
      end
    end

    resources :technologies, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :technology_categories, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end
  end



  namespace :admin, path: "admin" do
    root to: "products#index"
    get "sign_in" => "sessions#new"

    resources :clients do
      member do
        post :activate
      end
    end
    resources :products do
      member do
        get :new_version
        get :download_list
        put :upload_attachment
        post :create_version
        post :hide
        post :unhide
      end
    end
    resources :pages do
    end
    resources :orders, param: :articulus do
      collection do
        get :get_data
      end
    end
    resources :features do
    end
    resources :administrators do
    end
    resources :categories do
    end
    resources :subcategories do
    end

    resources :settings do
    end
    resources :contact_messages, path: "feedback" do
      collection do
        post :update_feedback_email
      end
    end
    resources :sessions, only: [:create] do
      collection do
        delete :destroy
      end
    end
  end

  namespace :front, path: "/" do
    root to: "pages#welcome"

    match "/404", :to => "errors#not_found", :via => :all

    get "sign_in" => "sessions#new"
    get "sign_up" => "users#new"

    get  "/orders"   => "orders#index"
    get  "/approved" => "orders#approved"
    post "/approved" => "orders#approved"
    post "/pay" => "orders#pay"

    get   "profile" => "users#profile"
    patch "profile" => "users#update_profile"

    get "oauth/callback"  => "oauths#callback"
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

    get "cart"     => "users#cart"
    get "checkout" => "base#checkout"

    resources :orders, param: :articulus do
      collection do
        post :stripe_success
        get  :paypal_success
      end
    end
    resources :contact_messages, only: [:create]
    resources :pages, path: "/", only: [] do
      collection do
        get :faq
        get :about_us, path: "aboutus"
        get :privacy
        get :terms_of_use
      end
    end
    resources :products, path: "readylists", only: [:index, :show] do
      collection do
        get :list
        get :subcategory
      end
      member do
        get    :download_example
        get    :download_list
        # TODO: Cart controller
        post   :add_to_cart
        delete :remove_from_cart
      end
    end
    resources :users do
      member do
        get :activate
      end
    end
    resources :sessions, only: [:create] do
      collection do
        delete :destroy
      end
    end
  end

  resources :password_resets
end

app/views/admin/pages/_form.haml
- if action == :new
  - panel_title = "New Page"
- elsif action == :edit
  - panel_title = "Edit Page"

%section.panel
  %header.panel-heading
    .panel-actions
    %h2.panel-title= panel_title
  .panel-body
    = f.input :target, label: "Target", input_html: {readonly: "readonly"}
    = f.input :meta_title, placeholder: 'Meta Title', label: "Meta Title"
    = f.input :meta_desc, placeholder: 'Meta Description', label: "Meta Description"
    = f.input :meta_keywords, placeholder: 'Meta Keywords', label: "Meta Keywords"

  %footer.panel-footer
    %button.btn.btn-primary Submit
    = link_to "Cancel", admin_pages_path, class: "btn btn-default"

app/views/admin/pages/edit.haml
%section.content-body{:role => "main"}
  %header.page-header
    %h2 Pages
    .right-wrapper.pull-right
      %ol.breadcrumbs
        %li
          = link_to admin_root_path do
            %i.fa.fa-home
        %li
          = link_to admin_pages_path do
            %span Pages
        %li
          %span= "Edit #{@page.target}"
      %a.sidebar-right-toggle{"data-open" => "sidebar-right"}
        %i.fa.fa-chevron-left
  .row
    .col-md-12.col-lg-12.col-xl-12
      = simple_form_for @page, url: admin_page_path(@page), method: "put", defaults: { required: false }, html: { class: "form-horizontal form-bordered" }, wrapper: :horizontal_form do |f|
        = render "admin/pages/form", f: f, action: :edit

app/views/admin/pages/index.haml
%section.content-body{:role => "main"}
  %header.page-header
    %h2 Pages
    .right-wrapper.pull-right
      %ol.breadcrumbs
        %li
          = link_to admin_root_path do
            %i.fa.fa-home
        %li
          %span Pages
      %a.sidebar-right-toggle{"data-open" => "sidebar-right"}
        %i.fa.fa-chevron-left
  / start: page
  = render "admin/shared/default_bootstrap_errors", locals: {flash: flash}
  .row
    .col-md-12.col-lg-12.col-xl-12
      %section.panel
        .panel-body
          -#.row
          -#  .col-sm-6
          -#    .mb-md
          -#      = link_to new_admin_page_path, class: "btn btn-primary" do
          -#        Add
          -#        %i.fa.fa-plus

          - if @pages.count > 0
            %table.table.table-bordered.table-striped.mb-none
              %thead
                %tr
                  %th Target
                  %th Meta Title
                  %th Meta Description
                  %th Meta Keywords
                  %th Actions
              %tbody
                - @pages.each do |page|
                  %tr
                    %td{width: "20%"}= page.target
                    %td{width: "20%"}= page.meta_title
                    %td{width: "20%"}= page.meta_desc
                    %td{width: "20%"}= page.meta_keywords
                    %td.actions{width: "20%"}
                      = link_to "Edit", edit_admin_page_path(page), class: "mb-xs mt-xs mr-xs btn btn-warning"

            .pull-right
              = pagination_(@pages, previous_label: "«", next_label: "»")
          - else
            .empty_list_notice
              No Pages to display