config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "front/pages#welcome"

  namespace :workroom, path: "workroom" do
    root to: 'lists#new'
    get "sign_in" => "sessions#new"

    resources :lists do
      member do
        get :download
      end
      collection do
        get :state
        get :check_company_count
      end
    end

    resources :industries, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :naics, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :sics, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :rankings, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :sessions, only: [:create] do
      collection do
        delete :destroy
      end
    end

    resources :technologies, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :technology_categories, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end
  end



  namespace :admin, path: "admin" do
    root to: "products#index"
    get "sign_in" => "sessions#new"

    resources :clients do
      member do
        post :activate
      end
    end
    resources :products do
      member do
        get :new_version
        get :download_list
        put :upload_attachment
        post :create_version
        post :hide
        post :unhide
      end
    end
    resources :pages do
    end
    resources :orders, param: :articulus do
      collection do
        get :get_data
      end
    end
    resources :features do
    end
    resources :administrators do
    end
    resources :categories do
    end
    resources :subcategories do
    end

    resources :settings do
    end
    resources :contact_messages, path: "feedback" do
      collection do
        post :update_feedback_email
      end
    end
    resources :sessions, only: [:create] do
      collection do
        delete :destroy
      end
    end
  end

  namespace :front, path: "/" do
    root to: "pages#welcome"

    match "/404", :to => "errors#not_found", :via => :all

    get "sign_in" => "sessions#new"
    get "sign_up" => "users#new"

    get  "/orders"   => "orders#index"
    get  "/approved" => "orders#approved"
    post "/approved" => "orders#approved"
    post "/pay" => "orders#pay"

    get   "profile" => "users#profile"
    patch "profile" => "users#update_profile"

    get "oauth/callback"  => "oauths#callback"
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

    get "cart"     => "users#cart"
    get "checkout" => "base#checkout"

    resources :orders, param: :articulus do
      collection do
        post :stripe_success
        get  :paypal_success
      end
    end
    resources :contact_messages, only: [:create]
    resources :pages, path: "/", only: [] do
      collection do
        get :faq
        get :about_us, path: "aboutus"
        get :privacy
        get :terms_of_use
      end
    end
    resources :products, path: "readylists", only: [:index, :show] do
      collection do
        get :list
        get :subcategory
      end
      member do
        get    :download_example
        get    :download_list
        # TODO: Cart controller
        post   :add_to_cart
        delete :remove_from_cart
      end
    end
    resources :users do
      member do
        get :activate
      end
    end
    resources :sessions, only: [:create] do
      collection do
        delete :destroy
      end
    end
  end

  resources :password_resets
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::BaseController

  def index
    page = params[:page].try(:to_i) || 1
    per_page = params[:per_page].try(:to_i) || 10

    @users = User.where.not(role: 'admin').order("created_at DESC").paginate(page: page, per_page: per_page)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.skip_activation_email = true
      @user.save
      flash[:notice] = 'User created'
      redirect_to admin_clients_url
    else
      render action: :new
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
    if @user
      render
    else
      flash[:error] = 'User not found'
      redirect_to admin_clients_url
    end
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user
      @user.assign_attributes(user_params)
      if @user.valid?
        @user.skip_activation_email = true
        @user.save
        flash[:notice] = 'User updated'
        redirect_to admin_clients_url
      else
        render action: :edit
      end
    else
      flash[:error] = 'User not found'
      redirect_to admin_clients_url
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if @user
      @user.destroy
      flash[:notice] = 'User destroyed'
    else
      flash[:error] = 'User not found'
    end
    redirect_to admin_clients_url
  end

  def activate
    @user = User.find_by(id: params[:id])
    if @user
      @user.skip_activation_success_email = true
      @user.activate!
      flash[:notice] = 'User activated'
    else
      flash[:error] = 'User not found'
    end
    redirect_to admin_clients_url
  end

private

  def user_params
    password = params.require(:user)[:password]
    if password.present?
      params[:user][:password_confirmation] = password
    end
    params.require(:user).permit!
  end
end

app/views/admin/clients/_form.haml
- if action == :new
  - panel_title = "New Client"
- elsif action == :edit
  - panel_title = "Edit Client"

%section.panel
  %header.panel-heading
    .panel-actions
    %h2.panel-title= panel_title
  .panel-body
    = f.input :first_name, placeholder: "First Name", label: "First Name"
    = f.input :last_name, placeholder: "Last Name",  label: "Last Name"
    = f.input :email, placeholder: "Email",  label: "Email"
    = f.input :company, placeholder: "Company",  label: "Company"
    = f.input :password, placeholder: "Password",  label: "Password", as: :string
    = f.input :country_code, as: :country, label: "Country"

  %footer.panel-footer
    %button.btn.btn-primary Submit
    = link_to "Cancel", admin_clients_path, class: "btn btn-default"

app/views/admin/clients/edit.haml
%section.content-body{:role => "main"}
  %header.page-header
    %h2 Clients
    .right-wrapper.pull-right
      %ol.breadcrumbs
        %li
          = link_to admin_root_path do
            %i.fa.fa-home
        %li
          = link_to admin_clients_path do
            %span Clients
        %li
          %span= "Edit #{@user.full_name}"
      %a.sidebar-right-toggle{"data-open" => "sidebar-right"}
        %i.fa.fa-chevron-left
  .row
    .col-md-12.col-lg-12.col-xl-12
      = simple_form_for @user, url: admin_client_path(@user), method: "put", defaults: { required: false }, html: { class: "form-horizontal form-bordered" }, wrapper: :horizontal_form do |f|
        = render "admin/clients/form", f: f, action: :edit

app/views/admin/clients/index.haml
%section.content-body{:role => "main"}
  %header.page-header
    %h2 Clients
    .right-wrapper.pull-right
      %ol.breadcrumbs
        %li
          = link_to admin_root_path do
            %i.fa.fa-home
        %li
          %span Clients
      %a.sidebar-right-toggle{"data-open" => "sidebar-right"}
        %i.fa.fa-chevron-left
  / start: page
  = render "admin/shared/default_bootstrap_errors", locals: {flash: flash}
  .row
    .col-md-12.col-lg-12.col-xl-12
      %section.panel
        .panel-body
          .row
            .col-sm-6
              .mb-md
                = link_to new_admin_client_path, class: "btn btn-primary" do
                  Add
                  %i.fa.fa-plus

          - if @users.count > 0
            %table.table.table-bordered.table-striped.mb-none
              %thead
                %tr
                  %th FirstName
                  %th LastName
                  %th Join Date
                  %th Actions
              %tbody
                - @users.each do |user|
                  %tr
                    %td{width: "25%"}= user.first_name
                    %td{width: "25%"}= user.last_name
                    %td{width: "25%"}= user.created_at.strftime("%m/%d/%Y")
                    %td.actions{width: "25%"}
                      = link_to "Edit", edit_admin_client_path(user), class: "mb-xs mt-xs mr-xs btn btn-warning"
                      = link_to "Delete", admin_client_path(user), method: "delete", data: {confirm: "Are you sure?"}, class: "mb-xs mt-xs mr-xs btn btn-danger"
                      - if user.activation_state == "pending"
                        = link_to "Activate", activate_admin_client_path(user), method: :post, class: "mb-xs mt-xs mr-xs btn btn-info"

            .pull-right
              = pagination_(@users, previous_label: "«", next_label: "»")
          - else
            .empty_list_notice
              No Clients to display

app/views/admin/clients/new.haml
%section.content-body{:role => "main"}
  %header.page-header
    %h2 Clients
    .right-wrapper.pull-right
      %ol.breadcrumbs
        %li
          = link_to admin_root_path do
            %i.fa.fa-home
        %li
          = link_to admin_clients_path do
            %span Clients
        %li
          %span New Client
      %a.sidebar-right-toggle{"data-open" => "sidebar-right"}
        %i.fa.fa-chevron-left
  .row
    .col-md-12.col-lg-12.col-xl-12
      = simple_form_for @user, url: admin_clients_path, method: "post", defaults: { required: false }, html: { class: "form-horizontal form-bordered" }, wrapper: :horizontal_form do |f|
        = render "admin/clients/form", f: f, action: :new