config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "front/pages#welcome"

  namespace :workroom, path: "workroom" do
    root to: 'lists#new'
    get "sign_in" => "sessions#new"

    resources :lists do
      member do
        get :download
      end
      collection do
        get :state
        get :check_company_count
      end
    end

    resources :industries, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :naics, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :sics, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :rankings, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :sessions, only: [:create] do
      collection do
        delete :destroy
      end
    end

    resources :technologies, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :technology_categories, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end
  end



  namespace :admin, path: "admin" do
    root to: "products#index"
    get "sign_in" => "sessions#new"

    resources :clients do
      member do
        post :activate
      end
    end
    resources :products do
      member do
        get :new_version
        get :download_list
        put :upload_attachment
        post :create_version
        post :hide
        post :unhide
      end
    end
    resources :pages do
    end
    resources :orders, param: :articulus do
      collection do
        get :get_data
      end
    end
    resources :features do
    end
    resources :administrators do
    end
    resources :categories do
    end
    resources :subcategories do
    end

    resources :settings do
    end
    resources :contact_messages, path: "feedback" do
      collection do
        post :update_feedback_email
      end
    end
    resources :sessions, only: [:create] do
      collection do
        delete :destroy
      end
    end
  end

  namespace :front, path: "/" do
    root to: "pages#welcome"

    match "/404", :to => "errors#not_found", :via => :all

    get "sign_in" => "sessions#new"
    get "sign_up" => "users#new"

    get  "/orders"   => "orders#index"
    get  "/approved" => "orders#approved"
    post "/approved" => "orders#approved"
    post "/pay" => "orders#pay"

    get   "profile" => "users#profile"
    patch "profile" => "users#update_profile"

    get "oauth/callback"  => "oauths#callback"
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

    get "cart"     => "users#cart"
    get "checkout" => "base#checkout"

    resources :orders, param: :articulus do
      collection do
        post :stripe_success
        get  :paypal_success
      end
    end
    resources :contact_messages, only: [:create]
    resources :pages, path: "/", only: [] do
      collection do
        get :faq
        get :about_us, path: "aboutus"
        get :privacy
        get :terms_of_use
      end
    end
    resources :products, path: "readylists", only: [:index, :show] do
      collection do
        get :list
        get :subcategory
      end
      member do
        get    :download_example
        get    :download_list
        # TODO: Cart controller
        post   :add_to_cart
        delete :remove_from_cart
      end
    end
    resources :users do
      member do
        get :activate
      end
    end
    resources :sessions, only: [:create] do
      collection do
        delete :destroy
      end
    end
  end

  resources :password_resets
end

app/controllers/front/base_controller.rb
class Front::BaseController < ApplicationController
  layout "front_base"

  before_action :set_user_cart
  before_action :set_redirect_cookies

  def checkout
    if current_user
      redirect_to
    else
      redirect_to front_sign_in_path, notice: "Please, sign in before checkout"
    end
  end

  def set_user_cart
    if current_user
      @user_cart = current_user.cart
      @user_cart = current_user.carts.create unless @user_cart
    elsif cookies[:cart_id]
      @user_cart = Cart.find_by(id: cookies[:cart_id])
      @user_cart = Cart.create unless @user_cart
    else
      @user_cart = Cart.create
    end
    cookies[:cart_id] = @user_cart.id
    calculate_cart(@user_cart)
  end

  def calculate_cart(cart)
    cart_products = @user_cart.cart_products
    total_price = 0
    cart_products.each do |cart_product|
      total_price += cart_product.price.to_f
    end
    @user_cart.order = Order.create! unless @user_cart.order
    @user_cart.order.update_attribute(:total_price, total_price)
  end

  def check_auth
    redirect_to front_sign_in_path, notice: "Please, sign in" unless current_user
  end

  def set_redirect_cookies
    cookies[:redirect_back_to] = request.env['PATH_INFO']
  end

  def redirect_with_saved_cookies(path, options = {})
    if cookies[:redirect_back_to]
      redirect_to cookies[:redirect_back_to], options
    else
      redirect_back_or_to path, options
    end
  end


end

app/controllers/front/contact_messages_controller.rb
class Front::ContactMessagesController < Front::BaseController

  def create
    @contact_message = ContactMessage.create(email: params[:email], name: params[:name], message: params[:message], user_id: current_user&.id)
    if @contact_message.valid?
      flash[:notice] = "Thanks! Your message has been successfully sent. We will contact you soon!"
      ContactMessagesMailer.delay.contact_message_email(@contact_message)
    else
      flash[:error] = "Sorry, error occurred"
    end
    redirect_to front_root_path
  end

end

app/controllers/front/errors_controller.rb
class Front::ErrorsController < Front::BaseController
  def not_found
    render(:status => 404)
  end
end

app/controllers/front/oauths_controller.rb
class Front::OauthsController < Front::BaseController
  skip_before_action :set_redirect_cookies

  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = params[:provider]
    if params[:error]
      flash[:alert] = "Failed to login from #{provider.titleize}!"
      return redirect_with_saved_cookies(front_root_path)
    end
    if @user = login_from(provider)
      @user.process_latest_cart(@user_cart)
      flash[:notice] = "Logged in from #{provider.titleize}!"
      redirect_with_saved_cookies front_root_path
    else
      begin
        @user = create_from(provider)
        @user.process_latest_cart(@user_cart)
        @user.activate!
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        if(@user.email)
          flash[:notice] = "Logged in from #{provider.titleize}!"
          redirect_with_saved_cookies front_root_path
        else
          redirect_to front_profile_path
        end
      rescue
        flash[:alert] = "Failed to login from #{provider.titleize}!"
        redirect_with_saved_cookies front_root_path
      end
    end
  end
end

app/controllers/front/orders_controller.rb
class Front::OrdersController < Front::BaseController
  before_action :check_auth, only: [:index]

  before_action :set_order,  only: [:show]

  skip_before_action :verify_authenticity_token
  skip_before_action :check_auth, only: [:notify]

  def index
    page = params[:page].try(:to_i) || 1
    per_page = params[:per_page].try(:to_i) || 10
    @orders = current_user.orders.order('id desc').where('payment_token is not null').paginate(page: page, per_page: per_page)
    @orders_count =  current_user.orders.count
  end

  def stripe_success
    @order = Order.find_by(id: params['order']['id'])

    token = params[:stripeToken]

    charge = Stripe::Charge.create(
      :amount => @order.total_price.to_i * 100,
      :currency => "usd",
      :description => "Charge from Listoteca.com for order #{@order.articulus}",
      :source => token,
    )

    if charge.paid
      @order.update_attributes(status: 'paid', transaction_id: charge.id, payment_method: 'stripe')
      redirect_to :front_approved
    else
      redirect_to :front_rejected
    end
  rescue Exception => e
    if e.class == Stripe::CardError
      flash[:error] = e.message
      redirect_to front_cart_url
    end
  end

  def paypal_success
    @order  = Order.find_by(payment_token: params['paymentId'])
    @paypal = PaypalInterface.new(@order)
    response = @paypal.execute(params["PayerID"] )
    if response
      @order.update_attributes(status: 'paid', transaction_id: params['token'], payment_method: 'paypal')
      redirect_to :front_approved
    else
      redirect_to :front_rejected
    end
  end

  def approved
    cart = Cart.joins(:cart_products).where('carts.user_id = ?', current_user.id).where('cart_products.id is not null').last
    @order = cart.order

    unless @order.payment_approved
      approval = CheckPaymentStatusService.new(@order).execute
      @order.update_attribute(:payment_approved, approval)
    end

    @user_cart = Cart.create
    @user_cart.update_attribute(:user_id, current_user.id)
    @gtm_event = 'Transaction'
    cookies[:cart_id] = @user_cart.id
  end

  def rejected
    flash[:notice] = "Something went wrong, please, try again."
  end

  def notify
    render head :ok
    # order = Order.find_by(payment_token: params['pay_key'])
    # if params['.status'] == 'COMPLETED'
    #   order.update_attributes(status: 'paid', transaction_id: params['transaction']['0']['.id_for_sender_txn'])
    # else
    #   flash[:notice] = "Sorry, but the transaction was unsuccessfull: #{params['transaction']['.id_for_sender_txn']}"
    # end
  end

private
  def set_order
    @order = Order.find_by(articulus: params[:articulus])
    unless (@order.present? && @order.cart.user == current_user)
      redirect_to front_404_url
    end

    unless @order.payment_approved
      approval = Front::CheckPaymentStatusService.new(@order).execute
      @order.update_attribute(:payment_approved, approval)
    end
  end

  def order_params
    params.permit!
  end
end

app/controllers/front/pages_controller.rb
class Front::PagesController < Front::BaseController
  def welcome
    @metadata = Page.find_by(target: 'welcome') || @metadata
  end

  def faq
    @metadata = Page.find_by(target: 'faq') || @metadata
  end

  def about_us
    @metadata = Page.find_by(target: 'aboutus') || @metadata
    render :layout => "about_layout"
  end

  def privacy
    @metadata = Page.find_by(target: 'privacy') || @metadata
  end

  def terms_of_use
    @metadata = Page.find_by(target: 'terms_of_use') || @metadata
  end

  def dummy
    render layout: false
  end
end

app/controllers/front/products_controller.rb
class Front::ProductsController < Front::BaseController
  before_action :check_auth, only: [:download_list]
  before_action :set_product, only: [:show, :download_example, :download_list, :add_to_cart, :remove_from_cart]


  # All code in init_list
  def index
    @categories    = Category.where(title: ['Industry', 'Geo'])

    @subcategories = params[:subcategories] || []
    @subcategories.map! { |s| s.to_i }

    @view          = params[:view] || 'list'

    @products      = Product.unhidden.latest_versions
    @products      = @products.filter_category(@subcategories) if @subcategories.present?
    @products      = @products.paginate(page: @page, per_page: @per_page)

    @metadata      = Page.find_by(target: 'readylists') || @metadata

    @page          = params[:page].try(:to_i)     || 1
    @per_page      = params[:per_page].try(:to_i) || 12

    render action: @view
  end


  def subcategory
    @subcategory   = params[:subcategory]
    @subcategories = params[:subcategories] || []
    if @subcategories.include?(@subcategory)
      @subcategories.reject!{ |s| s == @subcategory}
    else
      @subcategories << @subcategory
    end

    redirect_to front_products_path(subcategories: @subcategories)
  end

  def default_price_from_filter_value
    unless params[:product].blank?
      unless params[:product][:price_from].blank?
        params[:product][:price_from]
      end
    else
      nil
    end
  end

  def default_price_to_filter_value
    unless params[:product].blank?
      unless params[:product][:price_to].blank?
        params[:product][:price_to]
      end
    else
      nil
    end
  end

  def show
    @metadata = @product
    if @product.is_hidden
      flash[:error] = "Product not found"
      redirect_to front_root_url
    end
  end

  def download_example
    send_file @product.example_list.path
  end

  def download_list
    if current_user.bought_product?(@product.id)
      product_download = ProductDownload.find_or_create_by(user_id: current_user.id, product_id: @product.id, file_downloaded_at: Time.now)
      case params[:format]
      when "csv"
        product_download.add_csv
        send_file @product.csv_list.path, filename: "list_#{@product.articulus}.csv"
      when "xls"
        product_download.add_xls
        send_file @product.xls_list.path, filename: "list_#{@product.articulus}.xls"
      when "txt"
        product_download.add_txt
        send_file @product.txt_list.path, filename: "list_#{@product.articulus}.txt"
      end
    else
      redirect_to front_root_url, error: "Product is not bought yet"
    end
  end

  def add_to_cart
    unless @user_cart.cart_products.where(product_id: @product.id).any?
      price = @product.price_discounted || @product.price
      CartProduct.create(cart_id: @user_cart.id, product_id: @product.id, price: price)
    end
    redirect_to :back
  end

  def remove_from_cart
    if cart_product = CartProduct.find_by(cart_id: @user_cart.id, product_id:  @product.id)
      cart_product.destroy
    end
    redirect_to :back
  end

private

  def set_product
    @product = Product.find_by(articulus: params[:id])
    unless @product.present?
      redirect_to front_404_url
    end
  end

end

app/controllers/front/sessions_controller.rb
class Front::SessionsController < Front::BaseController
  skip_before_action :set_redirect_cookies
  
  def new
    @metadata = Page.find_by(target: 'sign_in') || @metadata
    if current_user
      redirect_with_saved_cookies front_root_path
    end
  end

  def create
    email = session_params[:email].downcase if session_params[:email]
    remember_me_flag = [1, true, '1', 'true'].include?(session_params[:remember])
    login_failed = false

    user = login(email, session_params[:password], remember_me_flag)
    login_failed = true unless user

    if login_failed
      flash[:error] = 'Login failed'
      redirect_to action: 'new'
    else
      user.process_latest_cart(@user_cart)
      flash[:notice] = 'Logged in successfully'
      redirect_with_saved_cookies front_root_path
    end
  end

  def destroy
    logout
    flash[:notice] = 'Logged out successfully'
    cookies.delete :cart_id
    redirect_with_saved_cookies front_root_path
  end

  private

  def session_params
    params.require(:user).permit!
  end
end

app/controllers/front/users_controller.rb
class Front::UsersController < Front::BaseController

  before_action :check_user_profile, only: [:profile, :update_profile]
  skip_before_action :set_redirect_cookies, only: [:new, :create, :activate]

  skip_before_action :verify_authenticity_token, only: :cart

  def new
    @metadata = Page.find_by(target: 'sign_up') || @metadata
    if current_user
      redirect_with_saved_cookies front_root_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      @user_cart.update(user_id: @user.id, status: "active")
      flash[:notice] = "Thanks! Activation instructions have been sent to your email account!"
      redirect_with_saved_cookies front_root_path
    else
      render action: "new"
    end
  end

  def profile
    @user = current_user
    @user.valid?
  end

  def update_profile
    @user = User.find(current_user.id)
    @user.assign_attributes(user_params.except(:password, :password_confirmation))
    if @user.valid?
      @user.save
      redirect_to front_profile_path
    else
      render action: "profile"
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      auto_login(@user)
      redirect_with_saved_cookies front_profile_path, notice: 'User was successfully activated.'
    else
      redirect_to(front_root_path, error: "Something went wrong")
    end
  end

  def cart
    url = Rails.application.routes.recognize_path(request.referrer)
    @last_controller = url[:controller]
    @last_action = url[:action]

    @recently_registred = (@last_controller == 'front/users' && @last_action == 'new') ? true : false

    @price = @user_cart.order.total_price
    if @price > 0
      @paypal = PaypalInterface.new(@user_cart.order)
    end
  end

private

  def check_user_profile
    redirect_to front_root_path unless current_user
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :company, :country_code )
  end
end

app/views/front/shared/_cart.haml
- if @user_cart.cart_products.any?
  %li#headerShop.dropdown.dropdown-mega.dropdown-mega-shop
    = link_to front_cart_path, class: "dropdown-toggle btn btn-primary cart-btn" do
      %i.fa.fa-shopping-cart
      = "Cart (#{@user_cart.cart_products.count}) - #{show_price(@user_cart.cart_products.sum(:price))}"
    %ul.dropdown-menu
      %li
        .dropdown-mega-content
          %table.cart
            %tbody
              - @user_cart.cart_products.each do |cart_product|
                %tr
                  %td.product-thumbnail
                    = link_to front_product_path(cart_product.product.articulus) do
                      = image_tag cart_product.product.public_cover(:medium), class: "img-responsive", height: "100", width: "100", style: "padding: 3px;"
                  %td.product-name
                    = link_to front_product_path(cart_product.product.articulus) do
                      = cart_product.product.title
                      %br/
                      %span.amount
                        %strong= show_price(cart_product.price)
                  %td.product-actions
                    = link_to remove_from_cart_front_product_path(cart_product.product.articulus), method: "delete", title: "Remove this item", class: "remove" do
                      %i.fa.fa-times
              %tr
                %td.actions{:colspan => "6"}
                  .actions-continue
                    = link_to front_cart_path, style: "display: inline;" do
                      %button.btn.pull-right.btn-primary{:type => "submit"}
                        Proceed to Checkout
                        %i.fa.fa-angle-right.ml-xs

app/views/front/shared/_footer.haml
%footer#footer.short
  .container
    .row
      .col-md-4
        %h4 About Listoteca
        %p
          Listoteca creates premium contact and industry lists of companies based on its own data processing technologies and a unique database that includes information about over 36 million companies. Leading companies around the world use our lists to accelerate sales and find new marketing opportunities...
          = link_to about_us_front_pages_path, class: "btn-flat btn-xs" do
            View More
            %i.fa.fa-arrow-right
        %hr.light/
        %p © Copyright 2016-2017. All Rights Reserved.
        %p
          = link_to("Terms of use", terms_of_use_front_pages_path)
          &nbsp
          &nbsp
          = link_to("Privacy Policy", privacy_front_pages_path)
          = image_tag('/comodo_secure_seal.png', style: "width: 90px;position: absolute;right: 10px;bottom: 22px;")
      .col-md-4
        .contact-details
          %h4 Get In Touch
          %ul.contact
            %li
              %p
                ALEXSONG PTE LTD
            %li
              %p
                %i.fa.fa-map-marker
                %strong Singapore:
                60 Albert street #10-04 OG Albert Complex Singapore (189969)
            %li
              %p
                %i.fa.fa-map-marker
                %strong United States:
                1900 Camden Ave, San Jose, CA 95124

            %li
              %p
                %i.fa.fa-phone
                (650) 382-2672
            %li
              %p
                %i.fa.fa-envelope
                %a{:href => "mailto:contact@listoteca.com"}  contact@listoteca.com

      .col-md-4
        %h4.mb-none Contact Sales
        = form_tag front_contact_messages_path, method: :post, id: "contactForm" do
          .row
            .form-group
              .col-md-6
                %label Your name *
                %input#name.form-control{"data-msg-required" => "Please enter your name.", :maxlength => "100", :name => "name", :required => "", :type => "text", :value => ""}/
              .col-md-6
                %label Your email address *
                %input#email.form-control{"data-msg-email" => "Please enter a valid email address.", "data-msg-required" => "Please enter your email address.", :maxlength => "100", :name => "email", :required => "", :type => "email", :value => ""}/
          .row
            .form-group
              .col-md-12
                %label Message *
                %textarea#message.form-control{"data-msg-required" => "Please enter your message.", :maxlength => "5000", :name => "message", :required => "", :rows => "2"}
          .row
            .col-md-4
              %input.btn.btn-primary.mb-xl{"data-loading-text" => "Loading...", :type => "submit", :value => "Send Message"}/
            .col-md-8
              #contactSuccess.alert.alert-success.hidden
                Message has been sent to us.
              #contactError.alert.alert-danger.hidden
                Error sending your message.

app/views/front/shared/_footer_about.haml
%footer#footer.short{style: "margin-top: 0;"}
  .container
    .row
      .col-md-4
        %h4 About Listoteca
        %p
          Listoteca creates premium contact and industry lists of companies based on its own data processing technologies and a unique database that includes information about over 36 million companies. Leading companies around the world use our lists to accelerate sales and find new marketing opportunities...
          = link_to about_us_front_pages_path, class: "btn-flat btn-xs" do
            View More
            %i.fa.fa-arrow-right
        %hr.light/
        %p © Copyright 2016-2017. All Rights Reserved.
        %p
          = link_to("Terms of use", terms_of_use_front_pages_path)
          &nbsp
          &nbsp
          = link_to("Privacy Policy", privacy_front_pages_path)
          = image_tag('/comodo_secure_seal.png', style: "width: 90px;position: absolute;right: 10px;bottom: 22px;")
      .col-md-4
        .contact-details
          %h4 Get In Touch
          %ul.contact
            %li
              %p
                ALEXSONG PTE LTD
            %li
              %p
                %i.fa.fa-map-marker
                %strong Singapore:
                60 Albert street #10-04 OG Albert Complex Singapore (189969)
            %li
              %p
                %i.fa.fa-map-marker
                %strong United States:
                1900 Camden Ave, San Jose, CA 95124

            %li
              %p
                %i.fa.fa-phone
                (650) 382-2672
            %li
              %p
                %i.fa.fa-envelope
                %a{:href => "mailto:contact@listoteca.com"}  contact@listoteca.com

      .col-md-4
        %h4.mb-none Contact Sales
        = form_tag front_contact_messages_path, method: :post, id: "contactForm" do
          .row
            .form-group
              .col-md-6
                %label Your name *
                %input#name.form-control{"data-msg-required" => "Please enter your name.", :maxlength => "100", :name => "name", :required => "", :type => "text", :value => ""}/
              .col-md-6
                %label Your email address *
                %input#email.form-control{"data-msg-email" => "Please enter a valid email address.", "data-msg-required" => "Please enter your email address.", :maxlength => "100", :name => "email", :required => "", :type => "email", :value => ""}/
          .row
            .form-group
              .col-md-12
                %label Message *
                %textarea#message.form-control{"data-msg-required" => "Please enter your message.", :maxlength => "5000", :name => "message", :required => "", :rows => "2"}
          .row
            .col-md-4
              %input.btn.btn-primary.mb-xl{"data-loading-text" => "Loading...", :type => "submit", :value => "Send Message"}/
            .col-md-8
              #contactSuccess.alert.alert-success.hidden
                Message has been sent to us.
              #contactError.alert.alert-danger.hidden
                Error sending your message.

app/views/front/shared/_nav_header.haml
%header#header.header-narrow{"data-plugin-options" => "{'stickyEnabled': true, 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': true, 'stickyStartAt': 0, 'stickySetTop': '0'}"}
  .header-body
    .header-container.container
      .header-row
        .header-column
          .header-logo
            = link_to front_root_path do
              %img{:alt => "Porto", :height => "40", :src => "/Listoteca_logo.png"}/
        .header-column
          .header-row
            .header-nav
              %button.btn.header-btn-collapse-nav{"data-target" => ".header-nav-main", "data-toggle" => "collapse"}
                %i.fa.fa-bars
              .header-nav-main.header-nav-main-effect-1.header-nav-main-sub-effect-1.collapse
                %nav
                  %ul#mainNav.nav.nav-pills
                    = active_link_to front_products_path, wrap_tag: :li, class: 'btn btn-default', style: 'border-color: red;' do
                      Ready lists
                    /= active_link_to faq_front_pages_path, wrap_tag: :li do
                    /  FAQ
                    = active_link_to about_us_front_pages_path, wrap_tag: :li do
                      About Us
                    - if current_user
                      = render "front/shared/user_logged_in_nav"
                    - else
                      = render "front/shared/no_user_nav"
                    = render "front/shared/cart"

app/views/front/shared/_no_user_nav.haml
%li#headerAccount.dropdown.dropdown-mega.dropdown-mega-signin.signin
  = link_to front_sign_in_path, class: "dropdown-toggle" do
    %i.fa.fa-user
    Sign In
  %ul.dropdown-menu
    %li
      .dropdown-mega-content
        .row
          .col-md-12
            .signin-form
              %span.dropdown-mega-sub-title Sign In
              = simple_form_for User.new, url: front_sessions_path, method: "post", defaults: { required: false } do |f|
                .row
                  .form-group
                    .col-md-12.p-none
                      %label Username or E-mail Address
                      = f.input :email, label: false, input_html: {class: "input-lg", tabindex: "1"}
                .row
                  .form-group
                    .col-md-12.p-none
                      %a#headerRecover.pull-right.mt-none.p-none{:href => "#"} (Lost Password?)
                      %label Password
                      = f.input :password, label: false, input_html: {class: "input-lg"}
                .row
                  .col-md-6.pl-none
                    = f.input :remember, as: :boolean, label: false, inline_label: 'Remember me', label_html: {style: "padding-left: 30px"}
                  .col-md-6.pr-none
                    %input.btn.btn-primary.pull-right.mb-xl{"data-loading-text" => "Loading...", :type => "submit", :value => "Login"}
                .row
                  .col-md-12.center
                    %hr
                    %ul.social-icons
                      %li.social-icons-facebook
                        = link_to front_auth_at_provider_path(:provider => :facebook), :title => "Facebook", style: "padding: 2px 5px 8px 5px" do
                          %i.fa.fa-facebook
                      %li.social-icons-linkedin
                        = link_to front_auth_at_provider_path(:provider => :linkedin), :title => "Linkedin", style: "padding: 2px 5px 8px 5px" do
                          %i.fa.fa-linkedin
              %p.sign-up-info
                Don't have an account yet?
                = link_to "Sign Up", front_sign_up_path, class: "btn btn-xs btn-danger btn-borders", style: 'padding: 1px 5px; border-width: 1px; border-bottom: 1px #d2322d solid;'
            .recover-form
              %span.dropdown-mega-sub-title Reset My Password
              %p Complete the form below to receive an email with the authorization code needed to reset                    your password.
              = form_tag password_resets_path, :method => :post do
                .row
                  .form-group
                    .col-md-12.p-none
                      %label E-mail Address
                      = text_field_tag :email, "", class: "form-control input-lg", type: "email"
                .row
                  .col-md-12.p-none
                    %input.btn.btn-primary.pull-right.mb-xl{"data-loading-text" => "Loading...", :type => "submit", :value => "Submit"}/
              %p.log-in-info
                Already have an account?
                %a#headerRecoverCancel.p-none.m-none.ml-xs{:href => "#"} Log In

app/views/front/shared/_page_header.haml
%section.page-header
  .container
    .row
      .col-md-12
        %ul.breadcrumb
          %li
            %a{:href => "#"} Home
          %li.active Pages
    .row
      .col-md-12
        %h1 Login

app/views/front/shared/_user_logged_in_nav.haml
%li#headerAccount.dropdown.dropdown-mega.dropdown-mega-signin.signin
  = link_to front_profile_path, class: "dropdown-toggle" do
    %i.fa.fa-user
    = current_user.full_name
  %ul.dropdown-menu.logged-in
    %li
      = link_to "Profile", front_profile_path
    %li
      = link_to "Orders", front_orders_path
    %li
      = link_to front_sessions_path, method: :delete do
        Log out