config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "front/pages#welcome"

  namespace :workroom, path: "workroom" do
    root to: 'lists#new'
    get "sign_in" => "sessions#new"

    resources :lists do
      member do
        get :download
      end
      collection do
        get :state
        get :check_company_count
      end
    end

    resources :industries, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :naics, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :sics, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :rankings, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :sessions, only: [:create] do
      collection do
        delete :destroy
      end
    end

    resources :technologies, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end

    resources :technology_categories, only: [:index] do
      collection do
        post :refresh
        get :state
      end
    end
  end



  namespace :admin, path: "admin" do
    root to: "products#index"
    get "sign_in" => "sessions#new"

    resources :clients do
      member do
        post :activate
      end
    end
    resources :products do
      member do
        get :new_version
        get :download_list
        put :upload_attachment
        post :create_version
        post :hide
        post :unhide
      end
    end
    resources :pages do
    end
    resources :orders, param: :articulus do
      collection do
        get :get_data
      end
    end
    resources :features do
    end
    resources :administrators do
    end
    resources :categories do
    end
    resources :subcategories do
    end

    resources :settings do
    end
    resources :contact_messages, path: "feedback" do
      collection do
        post :update_feedback_email
      end
    end
    resources :sessions, only: [:create] do
      collection do
        delete :destroy
      end
    end
  end

  namespace :front, path: "/" do
    root to: "pages#welcome"

    match "/404", :to => "errors#not_found", :via => :all

    get "sign_in" => "sessions#new"
    get "sign_up" => "users#new"

    get  "/orders"   => "orders#index"
    get  "/approved" => "orders#approved"
    post "/approved" => "orders#approved"
    post "/pay" => "orders#pay"

    get   "profile" => "users#profile"
    patch "profile" => "users#update_profile"

    get "oauth/callback"  => "oauths#callback"
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

    get "cart"     => "users#cart"
    get "checkout" => "base#checkout"

    resources :orders, param: :articulus do
      collection do
        post :stripe_success
        get  :paypal_success
      end
    end
    resources :contact_messages, only: [:create]
    resources :pages, path: "/", only: [] do
      collection do
        get :faq
        get :about_us, path: "aboutus"
        get :privacy
        get :terms_of_use
      end
    end
    resources :products, path: "readylists", only: [:index, :show] do
      collection do
        get :list
        get :subcategory
      end
      member do
        get    :download_example
        get    :download_list
        # TODO: Cart controller
        post   :add_to_cart
        delete :remove_from_cart
      end
    end
    resources :users do
      member do
        get :activate
      end
    end
    resources :sessions, only: [:create] do
      collection do
        delete :destroy
      end
    end
  end

  resources :password_resets
end

app/models/product.rb
class Product < ApplicationRecord

  include ActiveModel::Validations
  include ActiveModel::Dirty
  include ProductVersionable

  scope :filter_category, -> (product_ids) {[product_ids].flatten!; joins(:subcategories).where(subcategories: {id: product_ids})}
  scope :filter_price, -> (price_from, price_to) {where('price between ? and ?', price_from, price_to)}
  scope :unhidden, -> {where("is_hidden IS NOT TRUE")}

  has_many :product_subcategories, dependent: :destroy
  has_many :subcategories, through: :product_subcategories, source: :subcategory
  has_many :product_features, dependent: :destroy
  has_many :features, through: :product_features, source: :feature
  has_many :cart_products, dependent: :destroy

  before_create :generate_articulus
  before_create :set_dates_to_now

  after_validation :assign_attachment_file_names, on: :update

  validates :title, presence: true
  validates :description, presence: true
  validates :detailed_description, presence: true
  validates :price, presence: true, numericality: {greater_than_or_equal_to: 0.0, less_than: 1000000.0}
  validates :list_length, presence: true, numericality: {greater_than_or_equal_to: 0, less_than: 100000000.0}
  validates :last_updated_at_pub, presence: true
  validates :last_updated_at_internal, presence: true


  # validates :discount, numericality: {less_than_or_equal_to: 100.0, greater_than_or_equal_to: 0, allow_nil: true}
  validates_with ProductValidator

  has_attached_file :cover, styles: { medium: "300x300#" }, default_url: "/images/product_:style_missing.png"
  # validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/
  # validates :cover, attachment_presence: true

  has_attached_file :txt_list
  validates_attachment_content_type :txt_list, content_type: ["text/plain", "text/html"]
  #validates_format_of :txt_list_file_name, :with => %r{\.(txt)\z}
  #validates :txt_list, attachment_presence: true

  has_attached_file :xls_list
  validates_attachment_content_type :xls_list, content_type: ["application/x-ole-storage", "application/vnd.ms-excel", "application/xml", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]
  #validates_format_of :xls_list_file_name, :with => %r{\.(xls|xlsx)\z}i
  #validates :xls_list, attachment_presence: true

  has_attached_file :csv_list
  validates_attachment_content_type :csv_list, content_type: "text/plain"
  #validates_format_of :csv_list_file_name, :with => %r{\.(csv)\z}i, allow_nil: true
  #validates_attachment_content_type :csv_list, content_type: "text/plain"
  #validates :csv_list, attachment_presence: true

  has_attached_file :example_list
  validates_attachment_content_type :csv_list, content_type: ["text/plain", "text/html", "application/x-ole-storage", "application/vnd.ms-excel", "application/xml", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]
  #validates_format_of :example_list_file_name, :with => %r{\.(xls|txt|csv|xlsx)\z}i, allow_nil: true
  #validates :example_list, attachment_presence: true

  def public_cover(style = nil)
    cover.present? ? cover.url(style) : '/images/ls_product_icon.png'
  end

  def versionize_with(params)
    product_to_return = Product.new(params.merge(base_product_id: self.id))
    if !product_to_return.cover.present?
      product_to_return.cover = self.cover
    end
    return product_to_return
  end

  def assign_attachment_file_names
    if self.txt_list_updated_at_changed?
      extension = File.extname(txt_list_file_name).downcase
      self.txt_list.instance_write(:file_name, "#{articulus}_#{Time.now.to_i.to_s}#{extension}")
    end

    if self.xls_list_updated_at_changed?
      extension = File.extname(xls_list_file_name).downcase
      self.xls_list.instance_write(:file_name, "#{articulus}_#{Time.now.to_i.to_s}#{extension}")
    end
    if self.csv_list_updated_at_changed?
      extension = File.extname(csv_list_file_name).downcase
      self.csv_list.instance_write(:file_name, "#{articulus}_#{Time.now.to_i.to_s}#{extension}")
    end
    if self.example_list_updated_at_changed?
      extension = File.extname(example_list_file_name).downcase
      self.example_list.instance_write(:file_name, "#{articulus}_#{Time.now.to_i.to_s}_example#{extension}")
    end
  end

  def show_public_price
    (price.to_i == price) ? "$#{price.to_i}" : "$#{price}"
  end

  def show_discounted_price
    (price_discounted.to_i == price_discounted) ? "$#{price_discounted.to_i}" : "$#{price_discounted}"
  end

  def show_public_discount
    discount
  end

  def hide!
    self.update_attributes(is_hidden: true)
  end

  def show!
    self.update_attributes(is_hidden: false)
  end

  def generate_articulus
    options = [('A'..'Z'), (0..9)].map(&:to_a).flatten
    self.articulus = (0..5).map { options[rand(options.length)] }.join
    self.assign_attachment_file_names()
  end

  def set_dates_to_now
    self.last_updated_at_pub       = Date.today
    self.last_updated_at_internal  = Date.today
  end

  def downloads_by_user(user_id)
    product_downloads = ProductDownload.where(user_id: user_id).where(product_id: id)
  end

end

# == Schema Information
#
# Table name: products
#
#  id                        :integer          not null, primary key
#  title                     :string
#  articulus                 :string
#  base_product_id           :integer
#  cover_file_name           :string
#  cover_content_type        :string
#  cover_file_size           :integer
#  cover_updated_at          :datetime
#  txt_list_file_name        :string
#  txt_list_content_type     :string
#  txt_list_file_size        :integer
#  txt_list_updated_at       :datetime
#  xls_list_file_name        :string
#  xls_list_content_type     :string
#  xls_list_file_size        :integer
#  xls_list_updated_at       :datetime
#  csv_list_file_name        :string
#  csv_list_content_type     :string
#  csv_list_file_size        :integer
#  csv_list_updated_at       :datetime
#  example_list_file_name    :string
#  example_list_content_type :string
#  example_list_file_size    :integer
#  example_list_updated_at   :datetime
#  last_updated_at_pub       :datetime
#  last_updated_at_internal  :datetime
#  description               :text
#  detailed_description      :text
#  list_length               :integer
#  price                     :decimal(, )
#  discount                  :string
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  list_length_commentary    :text
#  is_latest_version         :boolean          default(TRUE)
#  structure                 :text
#  price_discounted          :decimal(, )
#  is_hidden                 :boolean          default(FALSE)
#  label_bg_color            :string           default("#e27c7c")
#  meta_title                :string
#  meta_desc                 :string
#  meta_keywords             :string
#

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  def index
    page = params[:page].try(:to_i) || 1
    per_page = params[:per_page].try(:to_i) || 10

    @products = Product.all.order("updated_at DESC").paginate(page: page, per_page: per_page)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.valid?
      @product.save
      flash[:notice] = 'Product created'
      render json: { is_valid: true,  redirect_url: admin_products_url }
    else
      p "Errors", @product.errors

      render json: { is_valid: false, errors: @product.errors }
    end
  end

  def edit
    @product = Product.includes(:subcategories, :features).find_by(id: params[:id])
    if @product
      render
    else
      flash[:error] = 'Product not found'
      redirect_to admin_products_url
    end
  end

  def update
    @product = Product.find_by(id: params[:id])
    if @product
      @product.assign_attributes(product_params)
      if @product.valid?
        @product.save
        flash[:notice] = 'Product updated'
        render json: { is_valid: true,  redirect_url: admin_products_url }
      else
        render json: { is_valid: false, errors: @product.errors }
      end
    else
      flash[:error] = 'Product not found'
      redirect_to admin_products_url
    end
  end

  def upload_attachment
    @product = Product.find(params[:id])
    if @product.update(product_params)
      render :text => 'ok'
    else
      render json: @product.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find_by(id: params[:id])
    if @product
      @product.destroy
      flash[:notice] = 'Product destroyed'
    else
      flash[:error] = 'Product not found'
    end
    redirect_to admin_products_url
  end

  def hide
    @product = Product.find_by(id: params[:id])
    if @product
      @product.hide!
      flash[:notice] = 'Product is now hidden and will not be shown on products page'
    else
      flash[:error]  = 'Product not found'
    end
    redirect_to admin_products_url
  end

  def unhide
    @product = Product.find_by(id: params[:id])
    if @product
      @product.show!
      flash[:notice] = 'Product is unhidden and will be shown on products page'
    else
      flash[:error] = 'Product not found'
    end
    redirect_to admin_products_url
  end

  def new_version
    edit()
  end

  def create_version
    @base_product = Product.find_by(id: params[:id])
    @product = @base_product.versionize_with(product_params)
    if @product.valid?
      @product.save
      flash[:notice] = 'Product created'
      render json: { is_valid: true,  redirect_url: admin_products_url }
    else
      render json: { is_valid: false, errors: @product.errors }
    end
  end

  def download_list
    @product = Product.find(params[:id])
    case params[:format]
    when "csv"
      send_file @product.csv_list.path, filename: "list_#{@product.articulus}.csv"
    when "xls"
      send_file @product.xls_list.path, filename: "list_#{@product.articulus}.xls"
    when "txt"
      send_file @product.txt_list.path, filename: "list_#{@product.articulus}.txt"
    end
  end

private

  def product_params
  #  dates_format = "%m/%d/%Y"
  #  last_updated_at_pub = params.require(:product)[:last_updated_at_pub]
  #  last_updated_at_internal = params.require(:product)[:last_updated_at_internal]
  #  params.require(:product)[:last_updated_at_pub] = Date.strptime(last_updated_at_pub, dates_format)
  #  params.require(:product)[:last_updated_at_internal] = Date.strptime(last_updated_at_internal, dates_format)
    params.require(:product).permit!
  end

end

app/controllers/front/products_controller.rb
class Front::ProductsController < Front::BaseController
  before_action :check_auth, only: [:download_list]
  before_action :set_product, only: [:show, :download_example, :download_list, :add_to_cart, :remove_from_cart]


  # All code in init_list
  def index
    @categories    = Category.where(title: ['Industry', 'Geo'])

    @subcategories = params[:subcategories] || []
    @subcategories.map! { |s| s.to_i }

    @view          = params[:view] || 'list'

    @products      = Product.unhidden.latest_versions
    @products      = @products.filter_category(@subcategories) if @subcategories.present?
    @products      = @products.paginate(page: @page, per_page: @per_page)

    @metadata      = Page.find_by(target: 'readylists') || @metadata

    @page          = params[:page].try(:to_i)     || 1
    @per_page      = params[:per_page].try(:to_i) || 12

    render action: @view
  end


  def subcategory
    @subcategory   = params[:subcategory]
    @subcategories = params[:subcategories] || []
    if @subcategories.include?(@subcategory)
      @subcategories.reject!{ |s| s == @subcategory}
    else
      @subcategories << @subcategory
    end

    redirect_to front_products_path(subcategories: @subcategories)
  end

  def default_price_from_filter_value
    unless params[:product].blank?
      unless params[:product][:price_from].blank?
        params[:product][:price_from]
      end
    else
      nil
    end
  end

  def default_price_to_filter_value
    unless params[:product].blank?
      unless params[:product][:price_to].blank?
        params[:product][:price_to]
      end
    else
      nil
    end
  end

  def show
    @metadata = @product
    if @product.is_hidden
      flash[:error] = "Product not found"
      redirect_to front_root_url
    end
  end

  def download_example
    send_file @product.example_list.path
  end

  def download_list
    if current_user.bought_product?(@product.id)
      product_download = ProductDownload.find_or_create_by(user_id: current_user.id, product_id: @product.id, file_downloaded_at: Time.now)
      case params[:format]
      when "csv"
        product_download.add_csv
        send_file @product.csv_list.path, filename: "list_#{@product.articulus}.csv"
      when "xls"
        product_download.add_xls
        send_file @product.xls_list.path, filename: "list_#{@product.articulus}.xls"
      when "txt"
        product_download.add_txt
        send_file @product.txt_list.path, filename: "list_#{@product.articulus}.txt"
      end
    else
      redirect_to front_root_url, error: "Product is not bought yet"
    end
  end

  def add_to_cart
    unless @user_cart.cart_products.where(product_id: @product.id).any?
      price = @product.price_discounted || @product.price
      CartProduct.create(cart_id: @user_cart.id, product_id: @product.id, price: price)
    end
    redirect_to :back
  end

  def remove_from_cart
    if cart_product = CartProduct.find_by(cart_id: @user_cart.id, product_id:  @product.id)
      cart_product.destroy
    end
    redirect_to :back
  end

private

  def set_product
    @product = Product.find_by(articulus: params[:id])
    unless @product.present?
      redirect_to front_404_url
    end
  end

end

app/views/admin/products/_attach_form.haml
%section.panel
  %header.panel-heading
    .panel-actions
    %h2.panel-title Attach lists
  .panel-body
    = f.input :id, placeholder: 'Id', as: :hidden, label: "Id", label_html: {data: {"error-label" => "id"}}, input_html: {data: {"error-input" => "id"}}
    .form-group{class: "#{f.object.errors.include?(:txt_list) ? 'has-error' : ''}"}
      %label.col-md-2.control-label{data: {"error-label" => "txt_list"}} Text List
      .col-md-10
        %div{:id => "txtUpload", :style => "margin-top: 7px;"}
    .form-group{class: "#{f.object.errors.include?(:xls_list) ? 'has-error' : ''}"}
      %label.col-md-2.control-label{data: {"error-label" => "xls_list"}} XLS List
      .col-md-10
        %div{:id => "xlsUpload", :style => "margin-top: 7px;"}
    .form-group{class: "#{f.object.errors.include?(:csv_list) ? 'has-error' : ''}"}
      %label.col-md-2.control-label{data: {"error-label" => "csv_list"}} CSV List
      .col-md-10
        %div{:id => "csvUpload", :style => "margin-top: 7px;"}
    .form-group{class: "#{f.object.errors.include?(:example_list) ? 'has-error' : ''}"}
      %label.col-md-2.control-label{data: {"error-label" => "example_list"}} Example List
      .col-md-10
        %div{:id => "exampleUpload", :style => "margin-top: 7px;"}
  %footer.panel-footer
  %button.btn.btn-primary{:id => "save"} Attach files

  

app/views/admin/products/edit.haml
%section.content-body{:role => "main"}
  %header.page-header
    %h2 Products
    .right-wrapper.pull-right
      %ol.breadcrumbs
        %li
          = link_to admin_root_path do
            %i.fa.fa-home
        %li
          = link_to admin_products_path do
            %span Products
        %li
          %span= "Edit #{@product.title}"
      %a.sidebar-right-toggle{"data-open" => "sidebar-right"}
        %i.fa.fa-chevron-left
  .row
    .col-md-12.col-lg-12.col-xl-12
      = simple_form_for @product, url: admin_product_path(@product), method: "put", defaults: { required: false }, html: { class: "form-horizontal form-bordered ", name: "admin_form" }, wrapper: :horizontal_form do |f|
        = render "admin/products/form", f: f, action: :edit
      = simple_form_for @product, url: admin_product_path(@product), method: "put", defaults: { required: false }, html: { class: "form-horizontal form-bordered ", name: "admin_form" }, wrapper: :horizontal_form do |f|
        = render "attach_form", f: f

app/views/admin/products/index.haml
%section.content-body{:role => "main"}
  %header.page-header
    %h2 Products
    .right-wrapper.pull-right
      %ol.breadcrumbs
        %li
          = link_to admin_root_path do
            %i.fa.fa-home
        %li
          %span Products
      %a.sidebar-right-toggle{"data-open" => "sidebar-right"}
        %i.fa.fa-chevron-left
  / start: page
  = render "admin/shared/default_bootstrap_errors", locals: {flash: flash}
  .row
    .col-md-12.col-lg-12.col-xl-12
      %section.panel
        .panel-body
          .row
            .col-sm-6
              .mb-md
                = link_to new_admin_product_path, class: "btn btn-primary" do
                  Add
                  %i.fa.fa-plus

          - if @products.count > 0
            %table.table.table-bordered.table-striped.mb-none
              %thead
                %tr
                  %th Cover
                  %th Title
                  %th Base Articulus
                  %th Version Articulus
                  %th Updated
                  %th Price
                  %th Actions
              %tbody
                - @products.each do |product|
                  %tr
                    %td{width: "1%"}= image_tag product.cover.url(:medium), width: "150px"
                    %td{width: "25%"}
                      - if product.is_hidden
                        %span.text-danger Hidden
                      - if product.is_latest_version
                        %span.text-success Latest Version
                      %span
                        = product.title
                    %td{width: "10%"}= product.get_base_articulus
                    %td{width: "10%"}= product.articulus
                    %td{width: "15%"}
                      Public: #{product.last_updated_at_pub}
                      Internal: #{product.last_updated_at_internal}
                    %td{width: "10%"}
                      Price: #{product.price}
                      Discounted: #{product.discount}
                    %td.actions{width: "49%"}
                      - if product.is_base_product?
                        = link_to "New Version", new_version_admin_product_path(product), method: :post, class: "mb-xs mt-xs mr-xs btn btn-success"
                      = link_to "Edit", edit_admin_product_path(product), class: "mb-xs mt-xs mr-xs btn btn-warning"
                      - if product.is_hidden
                        = link_to "Unhide", unhide_admin_product_path(product), method: :post, class: "mb-xs mt-xs mr-xs btn btn-info"
                      - else
                        = link_to "Hide", hide_admin_product_path(product), method: :post,class: "mb-xs mt-xs mr-xs btn btn-warning"
                      = link_to "Delete", admin_product_path(product), method: "delete", data: {confirm: "Are you sure? All versions of this product will be destroyed too"}, class: "mb-xs mt-xs mr-xs btn btn-danger"

            .pull-right
              = pagination_(@products, previous_label: "«", next_label: "»")
          - else
            .empty_list_notice
              No Products to display

app/views/admin/products/new.haml
%section.content-body{:role => "main"}
  %header.page-header
    %h2 Products
    .right-wrapper.pull-right
      %ol.breadcrumbs
        %li
          = link_to admin_root_path do
            %i.fa.fa-home
        %li
          = link_to admin_products_path do
            %span Products
        %li
          %span New
      %a.sidebar-right-toggle{"data-open" => "sidebar-right"}
        %i.fa.fa-chevron-left
  .row
    .col-md-12.col-lg-12.col-xl-12
      = simple_form_for @product, url: admin_products_path, method: "post", defaults: { required: false }, html: { class: "form-horizontal form-bordered", name: "admin_form" }, wrapper: :horizontal_form do |f|
        = render "admin/products/form", f: f, action: :new

app/views/admin/products/new_version.haml
%section.content-body{:role => "main"}
  %header.page-header
    %h2 Products
    .right-wrapper.pull-right
      %ol.breadcrumbs
        %li
          = link_to admin_root_path do
            %i.fa.fa-home
        %li
          = link_to admin_products_path do
            %span Products
        %li
          %span New Product Version
      %a.sidebar-right-toggle{"data-open" => "sidebar-right"}
        %i.fa.fa-chevron-left
  .row
    .col-md-12.col-lg-12.col-xl-12
      = simple_form_for @product, url: create_version_admin_product_path(@product), method: "post", defaults: { required: false }, html: { class: "form-horizontal form-bordered", name: "admin_form"  }, wrapper: :horizontal_form do |f|
        = render "admin/products/form", f: f, action: :new_version